name = "TheProject"
JULIA_CPU_THREADS = 4
JULIA_EDITOR = "emacs"
JULIA_NUM_THREADS = 4
authors = ["Oromion Aznar√°n caznaranl@uni.pe"]
version = "1.0.0"

[deps]
AsyPlots = "77e5a97a-5ef9-58df-9d21-21957d92d960"
GenericLinearAlgebra = "14197337-ba66-59df-a3e3-ca00e7dcff7a"
Latexify = "23fbe1c1-3f47-55db-b15f-69d7ec21a316"
LinearMaps = "7a12625a-238d-50fd-b39a-03d52299707e"
PGFPlotsX = "8314cec4-20b6-5062-9cdb-752b83310925"
PackageCompiler = "9b87118b-4619-50d2-8e1e-99f35a4d4d9d"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Polynomials = "f27b6e38-b328-58d1-80ce-0feddd5e7a45"
Primes = "27ebfcd6-29c5-5fa9-bf4b-fb8fc14df3ae"
PyCall = "438e738f-606a-5dbb-bf0a-cddfbfd45ab0"
SymPy = "24249f21-da20-56a4-8eb1-6a02cf4ae2e6"
TensorKit = "07d1fe3e-3e46-537d-9eac-e9e13d0d4cec"

[compat]
julia = "1.5.3"
